# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Analytics'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
# platform :ios, '10.0'

# # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'
